Algoritmo "ex090pdf"

Var

   A, B, S: Real

Procedimento Somador()
Inicio
      Escreval ("-----------------------------")
      S <- A + B
      Escreval ("A soma entre os valores é:",S)
      Escreval ("-----------------------------")
FimProcedimento

Inicio

      Escreval ("Iremos somar dois valores.")
      Escreva ("Digite um valor: ")
      Leia (A)
      Escreva ("Digite outro valor: ")
      Leia (B)
      Somador()

Fimalgoritmo