Algoritmo "ex093pdf"

Var

   I, F, Inc, C: Inteiro

Procedimento Contador (IN, FI, CR: Inteiro)
Inicio
      Para C <- IN ate FI passo CR faca
           Escreva (C," >>> ")
      FimPara
      Escreval ("FIM")
FimProcedimento

Inicio

      Escreva ("Inicio da contagem: ")
      Leia (I)
      Escreva ("Fim da contagem: ")
      Leia (F)
      Escreva ("Incremento: ")
      Leia (Inc)
      Contador (I, F, Inc)

Fimalgoritmo