Algoritmo "Cadastro-Usuario"
//
// Descrição   : Algoritmo que tem como função cadastrar o usuário.
// Autor(a)    : Eduardo Tenente
// Data atual  : 23/05/2026
Var

   nome, cidade: Caractere
   idade: Inteiro

Inicio

      Escreva ("Nome completo: ")
      Leia (nome)
      Escreva ("Idade: ")
      Leia (idade)
      Escreva ("Cidade onde reside: ")
      Leia (cidade)
      LimpaTela
      
      Escreval ("-------------------------------")
      Escreval (" Nome Completo: ",nome)
      Escreval (" Idade:",idade)
      Escreval (" Cidade onde mora: ",cidade)
      Escreval ("-------------------------------")
      
Fimalgoritmo