Algoritmo "ex03(P)"
Var

   nome: caractere
   salario: Real

Inicio

      Escreva ("Qual é o seu nome? ")
      Leia (nome)
      Escreva ("Qual é o seu salário? ")
      Leia (salario)
      Escreval ("O funcionário ",nome," tem um salário de R$",salario," em Junho")

Fimalgoritmo

// Crie um programa que leia o nome e o salário de um funcionário, mostrando no
// final uma mensagem.
// Ex:
// Nome do Funcionário: Maria do Carmo
// Salário: 1850,45
// O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.