Algoritmo "ex04(P)"
Var

   N1, N2, S: Inteiro

Inicio

      Escreva ("Digite um número: ")
      Leia (N1)
      Escreva ("Digite outro número: ")
      Leia (N2)
      S <- N1 + N2
      Escreval()
      Escreval ("A soma entre",N1," e",N2," é igual a",S)

Fimalgoritmo

// Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
// entre eles.
// Ex:
// Digite um valor: 8
// Digite outro valor: 5
// A soma entre 8 e 5 é igual a 13.