Algoritmo "ex05(P)"
Var

   N1, N2, S: Inteiro
   M: Real

Inicio

      Escreva ("Primeira nota: ")
      Leia (N1)
      Escreva ("Segunda nota: ")
      Leia (N2)
      S <- N1 + N2
      M <- S / 2
      Escreval()
      Escreva ("A média entre",N1," e",N2," é igual a",M)

Fimalgoritmo

// Faça um programa que leia as duas notas de um aluno em uma matéria e mostre
// na tela a sua média na disciplina.
// Ex:
// Nota 1: 4.5
// Nota 2: 8.5
// A média entre 4.5 e 8.5 é igual a 6.5