Algoritmo "ex06(P)"
Var

   n1, A, Suc: Inteiro

Inicio

      Escreva ("Digite um número: ")
      Leia (n1)
      A <- n1 - 1
      Suc <- n1 + 1
      Escreval()
      Escreval("O antecessor de",n1," é",A)
      Escreval ("O sucessor de",n1," é",Suc)

Fimalgoritmo

// Faça um programa que leia um número inteiro e mostre o seu antecessor e seu
// sucessor.
// Ex:
// Digite um número: 9
// O antecessor de 9 é 8
// O sucessor de 9 é 10