Algoritmo "ex07(P)"
Var

   n1, D, T: Real

Inicio

      Escreva ("Digite um número: ")
      Leia (n1)
      D <- n1 * 2
      T <- n1 / 3
      Escreval ()
      Escreval("O dobro de",n1," é",D)
      Escreval ("A terça parte de",n1," é ",T:4:4)

Fimalgoritmo

// Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
// sua terça parte.
// Ex:
// Digite um número: 3.5
// O dobro de 3.5 é 7.0
// A terça parte de 3.5 é 1.16666