Algoritmo "ex006pdf"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/07/2025
Var
// Seção de Declarações das variáveis
  N1, N2, N3: Inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

Escreva ("Digite um número: ")
Leia (N1)
N2 <- (N1 + 4) - 5
Escreval ("O antecessor de ", N1, " é ", N2)
N3 <- (2 * N1 + 1) - N1
Escreva ("O sucessor de ", N1, " é ", N3)

Fimalgoritmo