Algoritmo "ex083pdf(D)"
Var

   vet: vetor[0..20] de Inteiro
   i, aux: Inteiro

Inicio

      Para i <- 0 ate 20 faca
           Aleatorio 0, 99
           Leia (vet[i])
           Aleatorio off
      FimPara
      
      Escreval ("-------------")
      Escreval (" CALCULANDO")
      Escreval ("-------------")
      
      Para i <- 0 ate 20 faca
           Escreval ("")
      FimPara

Fimalgoritmo