Algoritmo "ex014pdf"

Var

   KM, Km_total, DIA, Dia_total, Pt: Real

Inicio

      Escreva ("Quantos Km percorreu? ")
      Leia (KM)
      Escreva ("Quantos dias o carro foi alugado? ")
      Leia (DIA)
      Dia_total <- 90 * DIA
      Km_total <- 0.20 * KM
      Pt <- Dia_total + Km_total
      Escreva ("O Preço Total a pagar é R$",Pt)
      
      
      //Carro = R$90 por dia//
      // 1Km = R$0,20 //
      // Calcule o Preço total a pagar //

Fimalgoritmo