Algoritmo "ex2(II)"
Var

   C, N: Inteiro
   D: Real

Inicio

      C <- 0
      Escreva ("Digite um número: ")
      Leia (N)
      Escreval()
      Escreval ("--------------------------")
      Escreval (" EXIBINDO OS DIVISORES...")
      Escreval ("--------------------------")
      Para C <- 1 ate 10 faca
           D <- N / C
           Escreval (N," /",C," = ",D:4:2)
           C <- C + 1
      FimPara

Fimalgoritmo

Solicite um número inteiro positivo e exiba todos os seus divisores.