Algoritmo "ex01"
Var

   N, aux: Inteiro

Inicio

      Escreva ("Informe um número: ")
      Leia (N)
      Se (N > 0) entao
         Escreval (N," é POSITIVO!")
      senao
           Se (N = 0) entao
              Escreval (N," é zero!")
           senao
                Se (N < 0) entao
                   Escreval (N," é NEGATIVO!")
                Fimse
           Fimse
      Fimse

Fimalgoritmo