Algoritmo "ex02"
Var

   N1, N2: Inteiro

Inicio

      Escreva ("Digite um número: ")
      Leia (N1)
      Escreva ("Digite outro número: ")
      Leia (N2)
      Se (N1 > N2) entao
         Escreval (N1," é maior que",N2," !")
      senao
           Se (N2 > N1) entao
              Escreval (N2," é maior que",N1," !")
           senao
                Escreval ("Os valores são iguais!")
           Fimse
      Fimse

Fimalgoritmo