Algoritmo "ex026pdf"

Var

   N1, N2: Inteiro

Inicio

      Escreva ("Digite um número: ")
      Leia (N1)
      Escreva ("Digite outro número: ")
      Leia (N2)
      
      Se (N1 > N2) entao
         Escreva ("O primeiro valor é maior")
      senao
         Se (N2 > N1) entao
            Escreva ("O segundo valor é maior")
         senao
            Escreva ("Não existe valor maior, os dois são iguais")
         Fimse
      Fimse
      
Fimalgoritmo